name: Release

on:
  workflow_run:
    workflows: ["Code Quality"]
    types:
      - completed
    branches:
      - main
  release:
    types: [published]

jobs:
  check-workflow-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Code quality checks passed
        run: echo "Code quality workflow completed successfully. Proceeding with build."

  build:
    name: Build Package
    needs: [check-workflow-success]
    # Only run for workflow_run events if the previous workflow succeeded
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv build --no-sources
      - name: Store built package
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 7

  # publish-testpypi:
  #   name: Publish to TestPyPI
  #   needs: [build]
  #   # Only run when a release is published
  #   if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
  #   runs-on: ubuntu-latest
  #   environment: release-testpypi
  #   permissions:
  #     id-token: write  # Required for trusted publishing
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/setup
  #     - name: Download built package
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: dist
  #         path: dist/
  #     - name: Publish to TestPyPI
  #       run: uv publish --index testpypi dist/*

  # publish-pypi:
  #   name: Publish to PyPI
  #   needs: [publish-testpypi]
  #   # Only run when a release is published
  #   if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
  #   runs-on: ubuntu-latest
  #   environment: release-pypi
  #   permissions:
  #     id-token: write  # Required for trusted publishing
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/setup
  #     - name: Test installation from TestPyPi
  #       run: uv pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple bada
  #     - name: Download built package
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: dist
  #         path: dist/
  #     - name: Publish to PyPI
  #       run: uv publish dist/*
